repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: mixed-line-ending

- repo: https://github.com/mxab/pre-commit-trivy.git
  rev: v0.16.0
  hooks:
    - id: trivyfs-docker
      args:
        - --severity=CRITICAL,HIGH,MEDIUM
        - --quiet
        - .
    - id: trivyconfig-docker
      args:
        - --severity=CRITICAL,HIGH,MEDIUM
        - --quiet
        - .

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
    - id: codespell

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.9
  hooks:
    - id: actionlint

- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.19.1
  hooks:
    - id: markdownlint-cli2

# - repo: https://github.com/commitizen-tools/commitizen
#   rev: v4.10.0
#   hooks:
#     - id: commitizen
#     - id: commitizen-branch
#       stages:
#         - pre-push

# ==============================
# LOCAL HOOKS
# REF: https://github.com/trufflesecurity/trufflehog/blob/939fabea556a4637a66ab79fb8fa5d0e8a436077/PreCommit.md#repository-specific-setup
- repo: local
  hooks:
    - id: trufflehog
      name: TruffleHog
      description: Detect secrets in your data.
      entry: bash -c 'trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail --no-update'
      language: system
      stages:
        - pre-commit
        - pre-push
