# REFS:
# https://github.com/actions/starter-workflows/blob/main/ci/go.yml
# https://github.com/mvdan/github-actions-golang
#

name: Build and Test - Feature Branches

permissions:
  contents: read

on:
  pull_request:
    branches:
      - feature-*

jobs:
  build:
    strategy:
      matrix:
        go-version: ['stable', 'oldstable']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v6.0.0
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: Check code formatting
        run: gofmt -s -w . && git diff --exit-code

      - name: Ensure dep definitions are up-to-date
        run: go mod tidy && git diff --exit-code

      - name: Download deps
        run: go mod download

      - name: Verify deps
        run: go mod verify

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.4  # does not work with commit hash; hosted on google git
      - name: Run govulncheck
        run: govulncheck -test ./...

      - name: Build
        run: go build -v ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9  # v8.0.0

      - name: Test
        run: go test -v -race -shuffle=on -coverprofile coverage.out ./...

      - name: Go Benchmark
        run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x ./...
